apiVersion: v1
kind: Service
metadata:
  name: Payment
spec:
  selector:
    app: Payment
  ports:
  - protocol: "TCP"
    port: 8001
    targetPort: 8001
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: db
spec:
  ports:
  - port: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Payment
spec:
  selector:
    matchLabels:
      app: Payment
  replicas: 4
  template:
    metadata:
      labels:
        app: Payment
    spec:
      containers:
      - name: Payment
        image: payment:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379

