version: '3.4'

services:
  vitereactstarter:
    image: vitereactstarter
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5174:5174
