version: '3.7'

services:
  inventory:
    image: inventory
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
  database:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - $PWD/data:/data
