apiVersion: v1
kind: Service
metadata:
  name: inventory
spec:
  selector:
    app: inventory
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: db
spec:
  ports:
  - port: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Inventory
spec:
  selector:
    matchLabels:
      app: Inventory
  replicas: 4
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: inventory:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
